# Generated by Django 4.0.2 on 2022-11-18 12:45

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_number', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('destination', models.CharField(max_length=100)),
                ('dimensions', models.CharField(max_length=100)),
                ('insurance_amount', models.FloatField()),
                ('final_delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RetailCenter',
            fields=[
                ('retail_center_number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_number', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.location')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_number', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.location')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationEvent',
            fields=[
                ('schedule_number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('deivery_route', models.CharField(max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.package')),
            ],
        ),
        migrations.CreateModel(
            name='Recieved',
            fields=[
                ('recieved_number', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.package')),
                ('retail_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.retailcenter')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_number', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.package'),
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_number', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Delivery.location')),
            ],
        ),
    ]
