# Generated by Django 4.1.4 on 2022-12-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportedBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='airport_number',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='plane_number',
        ),
        migrations.RemoveField(
            model_name='transportationevent',
            name='package',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_number',
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(default='ABC', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(default='Regular', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(default='In Transit', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='plane',
            name='flight_number',
            field=models.AutoField(default=123, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='retailcenter',
            name='package_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.package'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_address',
            field=models.CharField(default='123 Main St', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='dimensions',
            field=models.CharField(default='Small', max_length=100),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Recieved',
        ),
        migrations.AddField(
            model_name='transportedby',
            name='package_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.package'),
        ),
        migrations.AddField(
            model_name='transportedby',
            name='schedule_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.transportationevent'),
        ),
    ]
