# Generated by Django 4.1.4 on 2022-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_rename_package_number_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='City',
            field=models.CharField(default='New York', max_length=100),
        ),
    ]
