# Generated by Django 4.1.4 on 2022-12-13 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_location_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='City',
            new_name='city',
        ),
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
