# Generated by Django 4.1.4 on 2022-12-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_rename_city_location_city_package_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recipient',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
