# Generated by Django 4.1.4 on 2022-12-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0008_alter_transportationevent_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationevent',
            old_name='type',
            new_name='event_type',
        ),
    ]
