# Generated by Django 4.1.4 on 2022-12-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0009_rename_type_transportationevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Delivery.package'),
        ),
    ]
