# Generated by Django 4.1.4 on 2022-12-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0012_alter_location_location_number_historicallocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLocation',
        ),
    ]
